// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// This handler scaffold is generated once and will NOT be overwritten on regeneration.
//
// Add business logic in a companion partial file named FakeParameterExampleTestQueryHandler.Impl.cs:
//
//   using PetstoreApi.Commands;   // (or Queries)
//   using PetstoreApi.Services;
//
//   namespace PetstoreApi.Handlers;
//
//   public partial class FakeParameterExampleTestQueryHandler
//   {
//       private readonly IMyService _service;
//
//       public FakeParameterExampleTestQueryHandler(IMyService service) { _service = service; }
//
//       private async partial Task<Unit> ExecuteAsync(
//           FakeParameterExampleTestQuery request, CancellationToken cancellationToken)
//       {
//           // All mapping methods (MapDtoToDomain, MapDomainToDto, etc.)
//           // defined in this file are available here.
//       }
//   }
// </auto-generated>

using MediatR;
using PetstoreApi.Commands;
using PetstoreApi.Queries;
using PetstoreApi.Models;

namespace PetstoreApi.Handlers;

/// <summary>
/// Handler for FakeParameterExampleTestQuery.
/// Business logic is provided by a companion <c>FakeParameterExampleTestQueryHandler.Impl.cs</c> partial file.
/// </summary>
public partial class FakeParameterExampleTestQueryHandler : IRequestHandler<FakeParameterExampleTestQuery, Unit>
{
    public async Task<Unit> Handle(FakeParameterExampleTestQuery request, CancellationToken cancellationToken)
    {
        await Task.CompletedTask;
        return Unit.Value;
    }
}
