// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// This handler scaffold is generated once and will NOT be overwritten on regeneration.
//
// Add business logic in a companion partial file named FakeNullableExampleTestQueryHandler.Impl.cs:
//
//   using PetstoreApi.Commands;   // (or Queries)
//   using PetstoreApi.Services;
//
//   namespace PetstoreApi.Handlers;
//
//   public partial class FakeNullableExampleTestQueryHandler
//   {
//       private readonly IMyService _service;
//
//       public FakeNullableExampleTestQueryHandler(IMyService service) { _service = service; }
//
//       private async partial Task<TestNullableDto> ExecuteAsync(
//           FakeNullableExampleTestQuery request, CancellationToken cancellationToken)
//       {
//           // All mapping methods (MapDtoToDomain, MapDomainToDto, etc.)
//           // defined in this file are available here.
//       }
//   }
// </auto-generated>

using MediatR;
using PetstoreApi.Commands;
using PetstoreApi.Queries;
using PetstoreApi.Models;
using PetstoreApi.DTOs;

namespace PetstoreApi.Handlers;

/// <summary>
/// Handler for FakeNullableExampleTestQuery.
/// Business logic is provided by a companion <c>FakeNullableExampleTestQueryHandler.Impl.cs</c> partial file.
/// </summary>
public partial class FakeNullableExampleTestQueryHandler : IRequestHandler<FakeNullableExampleTestQuery, TestNullableDto>
{
    /// <summary>Dispatches to <see cref="ExecuteAsync"/> implemented in the companion partial file.</summary>
    public Task<TestNullableDto> Handle(FakeNullableExampleTestQuery request, CancellationToken cancellationToken)
        => ExecuteAsync(request, cancellationToken);

    /// <summary>
    /// Provide the business logic for this handler in a companion <c>FakeNullableExampleTestQueryHandler.Impl.cs</c> partial file.
    /// All mapping methods below (MapDtoToDomain, MapDomainToDto, enum helpers) are available to the implementation.
    /// </summary>
    private partial Task<TestNullableDto> ExecuteAsync(FakeNullableExampleTestQuery request, CancellationToken cancellationToken);

    // ========================================================================
    // Mapping methods — available to your ExecuteAsync implementation
    // ========================================================================

    /// <summary>
    /// Map domain entity <see cref="TestNullable"/> to <see cref="TestNullableDto"/>.
    /// </summary>
    private static TestNullableDto MapDomainToDto(TestNullable model)
    {
        return new TestNullableDto
        {
            Name = model.Name,
            NullableName = model.NullableName,
        };
    }

}
