// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// This handler scaffold is generated once and will NOT be overwritten on regeneration.
//
// Add business logic in a companion partial file named FindPetsByStatusQueryHandler.Impl.cs:
//
//   using PetstoreApi.Commands;   // (or Queries)
//   using PetstoreApi.Services;
//
//   namespace PetstoreApi.Handlers;
//
//   public partial class FindPetsByStatusQueryHandler
//   {
//       private readonly IMyService _service;
//
//       public FindPetsByStatusQueryHandler(IMyService service) { _service = service; }
//
//       private async partial Task<IEnumerable<PetDto>> ExecuteAsync(
//           FindPetsByStatusQuery request, CancellationToken cancellationToken)
//       {
//           // All mapping methods (MapDtoToDomain, MapDomainToDto, etc.)
//           // defined in this file are available here.
//       }
//   }
// </auto-generated>

using MediatR;
using PetstoreApi.Commands;
using PetstoreApi.Queries;
using PetstoreApi.Models;
using PetstoreApi.DTOs;

namespace PetstoreApi.Handlers;

/// <summary>
/// Handler for FindPetsByStatusQuery.
/// Business logic is provided by a companion <c>FindPetsByStatusQueryHandler.Impl.cs</c> partial file.
/// </summary>
public partial class FindPetsByStatusQueryHandler : IRequestHandler<FindPetsByStatusQuery, IEnumerable<PetDto>>
{
    /// <summary>Dispatches to <see cref="ExecuteAsync"/> implemented in the companion partial file.</summary>
    public Task<IEnumerable<PetDto>> Handle(FindPetsByStatusQuery request, CancellationToken cancellationToken)
        => ExecuteAsync(request, cancellationToken);

    /// <summary>
    /// Provide the business logic for this handler in a companion <c>FindPetsByStatusQueryHandler.Impl.cs</c> partial file.
    /// All mapping methods below (MapDtoToDomain, MapDomainToDto, enum helpers) are available to the implementation.
    /// </summary>
    private partial Task<IEnumerable<PetDto>> ExecuteAsync(FindPetsByStatusQuery request, CancellationToken cancellationToken);

    // ========================================================================
    // Mapping methods — available to your ExecuteAsync implementation
    // ========================================================================

    /// <summary>
    /// Map domain entity <see cref="Pet"/> to <see cref="PetDto"/>.
    /// </summary>
    private static PetDto MapDomainToDto(Pet model)
    {
        return new PetDto
        {
            Id = model.Id,
            Category = model.Category != null ? new CategoryDto { Id = model.Category.Id, Name = model.Category.Name } : null,
            Name = model.Name,
            PhotoUrls = model.PhotoUrls,
            Tags = model.Tags?.Select(t => new TagDto { Id = t.Id, Name = t.Name }).ToList(),
            Status = MapStatusModelToDto(model.Status),
        };
    }


    private static PetDto.StatusEnum MapStatusModelToDto(Pet.StatusEnum source)
    {
        return source switch
        {
            Pet.StatusEnum.AvailableEnum => PetDto.StatusEnum.AvailableEnum,
            Pet.StatusEnum.PendingEnum => PetDto.StatusEnum.PendingEnum,
            Pet.StatusEnum.SoldEnum => PetDto.StatusEnum.SoldEnum,
            _ => PetDto.StatusEnum.AvailableEnum,
        };
    }

}
