// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// This handler scaffold is generated once and will NOT be overwritten on regeneration.
//
// Add business logic in a companion partial file named GetInventoryQueryHandler.Impl.cs:
//
//   using PetstoreApi.Commands;   // (or Queries)
//   using PetstoreApi.Services;
//
//   namespace PetstoreApi.Handlers;
//
//   public partial class GetInventoryQueryHandler
//   {
//       private readonly IMyService _service;
//
//       public GetInventoryQueryHandler(IMyService service) { _service = service; }
//
//       private async partial Task<Dictionary<string, int>> ExecuteAsync(
//           GetInventoryQuery request, CancellationToken cancellationToken)
//       {
//           // All mapping methods (MapDtoToDomain, MapDomainToDto, etc.)
//           // defined in this file are available here.
//       }
//   }
// </auto-generated>

using MediatR;
using PetstoreApi.Commands;
using PetstoreApi.Queries;
using PetstoreApi.Models;
using PetstoreApi.DTOs;

namespace PetstoreApi.Handlers;

/// <summary>
/// Handler for GetInventoryQuery.
/// Business logic is provided by a companion <c>GetInventoryQueryHandler.Impl.cs</c> partial file.
/// </summary>
public partial class GetInventoryQueryHandler : IRequestHandler<GetInventoryQuery, Dictionary<string, int>>
{
    /// <summary>Dispatches to <see cref="ExecuteAsync"/> implemented in the companion partial file.</summary>
    public Task<Dictionary<string, int>> Handle(GetInventoryQuery request, CancellationToken cancellationToken)
        => ExecuteAsync(request, cancellationToken);

    /// <summary>
    /// Provide the business logic for this handler in a companion <c>GetInventoryQueryHandler.Impl.cs</c> partial file.
    /// All mapping methods below (MapDtoToDomain, MapDomainToDto, enum helpers) are available to the implementation.
    /// </summary>
    private partial Task<Dictionary<string, int>> ExecuteAsync(GetInventoryQuery request, CancellationToken cancellationToken);

    // ========================================================================
    // Mapping methods — available to your ExecuteAsync implementation
    // ========================================================================

}
