// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// This handler scaffold is generated once and will NOT be overwritten on regeneration.
//
// Add business logic in a companion partial file named GetOrderByIdQueryHandler.Impl.cs:
//
//   using PetstoreApi.Commands;   // (or Queries)
//   using PetstoreApi.Services;
//
//   namespace PetstoreApi.Handlers;
//
//   public partial class GetOrderByIdQueryHandler
//   {
//       private readonly IMyService _service;
//
//       public GetOrderByIdQueryHandler(IMyService service) { _service = service; }
//
//       private async partial Task<OrderDto> ExecuteAsync(
//           GetOrderByIdQuery request, CancellationToken cancellationToken)
//       {
//           // All mapping methods (MapDtoToDomain, MapDomainToDto, etc.)
//           // defined in this file are available here.
//       }
//   }
// </auto-generated>

using MediatR;
using PetstoreApi.Commands;
using PetstoreApi.Queries;
using PetstoreApi.Models;
using PetstoreApi.DTOs;

namespace PetstoreApi.Handlers;

/// <summary>
/// Handler for GetOrderByIdQuery.
/// Business logic is provided by a companion <c>GetOrderByIdQueryHandler.Impl.cs</c> partial file.
/// </summary>
public partial class GetOrderByIdQueryHandler : IRequestHandler<GetOrderByIdQuery, OrderDto>
{
    /// <summary>Dispatches to <see cref="ExecuteAsync"/> implemented in the companion partial file.</summary>
    public Task<OrderDto> Handle(GetOrderByIdQuery request, CancellationToken cancellationToken)
        => ExecuteAsync(request, cancellationToken);

    /// <summary>
    /// Provide the business logic for this handler in a companion <c>GetOrderByIdQueryHandler.Impl.cs</c> partial file.
    /// All mapping methods below (MapDtoToDomain, MapDomainToDto, enum helpers) are available to the implementation.
    /// </summary>
    private partial Task<OrderDto> ExecuteAsync(GetOrderByIdQuery request, CancellationToken cancellationToken);

    // ========================================================================
    // Mapping methods — available to your ExecuteAsync implementation
    // ========================================================================

    /// <summary>
    /// Map domain entity <see cref="Order"/> to <see cref="OrderDto"/>.
    /// </summary>
    private static OrderDto MapDomainToDto(Order model)
    {
        return new OrderDto
        {
            Id = model.Id,
            PetId = model.PetId,
            Quantity = model.Quantity,
            ShipDate = model.ShipDate,
            Status = MapStatusModelToDto(model.Status),
            Complete = model.Complete,
        };
    }


    private static OrderDto.StatusEnum MapStatusModelToDto(Order.StatusEnum source)
    {
        return source switch
        {
            Order.StatusEnum.PlacedEnum => OrderDto.StatusEnum.PlacedEnum,
            Order.StatusEnum.ApprovedEnum => OrderDto.StatusEnum.ApprovedEnum,
            Order.StatusEnum.DeliveredEnum => OrderDto.StatusEnum.DeliveredEnum,
            _ => OrderDto.StatusEnum.PlacedEnum,
        };
    }

}
